<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <Folder Include="UseCases\OrderItems\"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\LogisticsFlow.Domain\LogisticsFlow.Domain.csproj"/>
    </ItemGroup>

</Project>
