<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
      <UserSecretsId>4e057124-1ccf-46d0-b06b-145005246e4a</UserSecretsId>
  </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.11" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.11">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\LogisticsFlow.Application\LogisticsFlow.Application.csproj" />
        <ProjectReference Include="..\LogisticsFlow.Domain\LogisticsFlow.Domain.csproj" />
        <ProjectReference Include="..\LogisticsFlow.Infrastructure\LogisticsFlow.Infrastructure.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Folder Include="Endpoints\OrderItem\" />
    </ItemGroup>

</Project>
